export const MP_GATEWAY = Symbol('MP_GATEWAY');
export const CREATE_MP_PREFERENCE_USE_CASE = Symbol('CREATE_MP_PREFERENCE_USE_CASE');
export const PROCESS_MP_WEBHOOK_USE_CASE = Symbol('PROCESS_MP_WEBHOOK_USE_CASE');
