export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const DELIVERY_RATE_REPOSITORY = Symbol('DELIVERY_RATE_REPOSITORY');
export const PLACE_ORDER_USE_CASE = Symbol('PLACE_ORDER_USE_CASE');
export const GET_ORDER_USE_CASE = Symbol('GET_ORDER_USE_CASE');
export const GET_USER_ORDERS_USE_CASE = Symbol('GET_USER_ORDERS_USE_CASE');
export const UPDATE_ORDER_STATUS_USE_CASE = Symbol('UPDATE_ORDER_STATUS_USE_CASE');
