export const STORE_SETTINGS_REPOSITORY = Symbol('STORE_SETTINGS_REPOSITORY');
export const GET_STORE_SETTINGS_USE_CASE = Symbol('GET_STORE_SETTINGS_USE_CASE');
export const UPDATE_STORE_SETTINGS_USE_CASE = Symbol('UPDATE_STORE_SETTINGS_USE_CASE');
