export const REVIEW_REPOSITORY = Symbol('REVIEW_REPOSITORY');
export const ORDER_QUERY_PORT = Symbol('ORDER_QUERY_PORT');
export const GET_PRODUCT_REVIEWS_USE_CASE = Symbol('GET_PRODUCT_REVIEWS_USE_CASE');
export const CREATE_REVIEW_USE_CASE = Symbol('CREATE_REVIEW_USE_CASE');
