export const EMAIL_PORT = Symbol('EMAIL_PORT');
export const SEND_ORDER_CONFIRMATION_USE_CASE = Symbol('SEND_ORDER_CONFIRMATION_USE_CASE');
export const SEND_ORDER_RECEIVED_NOTIFICATION_USE_CASE = Symbol('SEND_ORDER_RECEIVED_NOTIFICATION_USE_CASE');
