export const CART_REPOSITORY = Symbol('CART_REPOSITORY');
export const ADD_ITEM_TO_CART_USE_CASE = Symbol('ADD_ITEM_TO_CART_USE_CASE');
export const GET_CART_USE_CASE = Symbol('GET_CART_USE_CASE');
export const UPDATE_CART_ITEM_USE_CASE = Symbol('UPDATE_CART_ITEM_USE_CASE');
export const REMOVE_CART_ITEM_USE_CASE = Symbol('REMOVE_CART_ITEM_USE_CASE');
export const MERGE_CARTS_USE_CASE = Symbol('MERGE_CARTS_USE_CASE');
export const CLEAR_CART_USE_CASE = Symbol('CLEAR_CART_USE_CASE');
